# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_accleterated_sgd.ipynb.

# %% auto 0
__all__ = ['BaseSchedCB', 'BatchSchedCB', 'RecorderCB']

# %% ../nbs/12_accleterated_sgd.ipynb 1
import torch

from .datasets import *
from .conv import *
from .learner import *
from .activations import *
from .init import *

# %% ../nbs/12_accleterated_sgd.ipynb 70
class BaseSchedCB(Callback):
    def __init__(self, sched): self.sched = sched
    def before_fit(self, learn): self.schedo = self.sched(learn.opt)
    def step(self, learn):
        if learn.training: self.schedo.step()

# %% ../nbs/12_accleterated_sgd.ipynb 72
class BatchSchedCB(BaseSchedCB):
    def before_batch(self, learn): self.step(learn)

# %% ../nbs/12_accleterated_sgd.ipynb 74
class RecorderCB(Callback):
    def __init__(self, **d): self.d = d
    def before_fit(self, learn):
        self.recs = {k:[] for k in self.d}
        self.pg = learn.opt.param_groups[0]
    
    def after_batch(self, learn):
        if not learn.training: return
        for k,v in self.d.items():
            self.recs[k].append(v(self))
    
    def plot(self):
        for k,v in self.recs.items():
            plt.plot(v, label=k)
            plt.legend()
            plt.show()
